

<h3 class="card-title text-center" id="aboutTitle">A Propos</h3>

<div id="aboutPage">

  <div class="aboutPageText">
    <p> Amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum,
    nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis.
    Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum.
    Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod,
    sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae.
     Amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum,
    nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis.
    Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum.
    Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod,
    sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae.</p>
  </div>

 <div class="aboutPageText">
    <p> Amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum,
    nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis.
    Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum.
    Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod,
    sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae.
     Amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum,
    nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis.
    Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum.
    Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod,
    sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae.</p>
  </div>

</div>


