

<!-- ******************************FORM************************* -->

<form  method="POST" class="contactForm" action="index.php?page=cible">
  <div class="forms">

    <label class="formLabel">Nom</label>
    <input class="nameInput" type="text" required>
    <span class='lastNameError'></span>
  </div>
 
  <div class="forms">
    <label class="formLabel">Email</label>
    <input class="emailInput" type="email" required>
    <span class='emailError'></span>
  </div>

   <div class="forms">
    <label class="formLabel">Tel:</label>
    <input  class="phoneInput" type="tel" required>
    <span class='phoneError'></span>
  </div>

  <div class="forms">
    <label class="formLabel">Message</label>
   <textarea class="textareaInput" type="text" required></textarea>
   <span class='textareaError'></span>
  </div>

  <button type="submit" class="submitButton">Envoyer</button>
</form>
<!-- ******************************TEXT-CARD************************* -->

<div class="card" style="width: 100%;">
  <div class="card-body">
    <p class="card-text text-center">Vous pouvez utiliser les informations suivantes ou le formulaire de contact ci-dessus pour me contacter.</p>
    <p class="card-text text-center">scra@mail.com</p>
    <p class="card-text text-center">06 23 34 69 74</p>
    <p class="card-text text-center">Site réalisé par http://ainaweb.site/</p>
  </div>
</div>
