
<form  class="contactForm">
  <div class="homeForm">

    <label class="formLabel">Nom</label>
    <input class="nameInput" type="text" required>
    <span class='lastNameError'></span>
  </div>
 
  <div class="homeForm">
    <label class="formLabel">Email</label>
    <input class="emailInput" type="email" required>
    <span class='emailError'></span>
  </div>

   <div class="homeForm">
    <label class="formLabel">Tel:</label>
    <input  class="phoneInput" type="tel" required>
    <span class='phoneError'></span>
  </div>

  <div class="homeForm">
    <label class="formLabel">Message</label>
   <textarea class="textareaInput" required></textarea>
   <span class='textareaError'></span>
  </div>

  <button class="homePageFormButton">Envoyer</button>
</form>
