<!-- *************************************HOME PAGE*************************************** -->

<div id="homePage" class="card bg-dark text-white">
  <img src="img\acceuil9.jpg" class="card-img" alt="bureau">
  <div class="card-img-overlay">
    <h5 class="card-title">Jon Doe</h5>
    <p class="card-text">Architecte DE HMONP</p>
  </div>
</div>

<!-- ************************************FIRST PROJECT********************************** -->

<div class="projects">

 <div class="project"> 
  <h3>Maecenas dignissim</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae</p>
</div>

<div class="borderAnimation">
  <img src="img\projet1.jpg" alt ="image d'une maison verte" class="imgProject">
</div>

  


<!-- ************************************SECOND PROJECT********************************** -->
<div class="project"> 
  <h3>Nulla facilisi</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae</p>
  </div>

  <div class="borderAnimation">
    <img src="img\projet2.jpg" alt="image d'une maison " class="imgProject">
  </div>
  


<!-- ************************************THIRD PROJECT********************************** -->
<div class="project"> 
  <h3>Suspendisse commodo</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae</p>
</div>

<div class="borderAnimation">
  <img src="img\projet3.jpg" alt ="image d'une fontaine" class="imgProject">
  </div>

</div>

</div>


<!-- ************************************ABOUT SECTION********************************** -->

<h3 class="aboutTitle text-center">A Propos</h3>

<div class="aboutSection">
   <div class="text-center"><h3> Maecenas sed </h3>
    <p class="aboutText text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae</p>
   </div>

   <div class="text-center"><h3> Maecenas sed </h3>
    <p class="aboutText text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae</p>
   </div>

</div>
<!-- ************************************FORM SECTION********************************** -->

<form  class="homePageForm">
  <div class="homeForm">

    <label class="formLabel">Nom</label>
    <input class="nameInput" type="text" required>
    <span class='lastNameError'></span>
  </div>
 
  <div class="homeForm">
    <label class="formLabel">Email</label>
    <input class="emailInput" type="email" required>
    <span class='emailError'></span>
  </div>

   <div class="homeForm">
    <label class="formLabel">Tel:</label>
    <input  class="phoneInput" type="tel" required>
    <span class='phoneError'></span>
  </div>

  <div class="homeForm">
    <label class="formLabel">Message</label>
   <textarea class="textareaInput" required></textarea>
   <span class='textareaError'></span>
  </div>

  <button class="homePageFormButton">Envoyer</button>
</form>

