<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8"/>
    <meta name="description" content=""/>
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dessein</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href="css/style.css">
  </head>
<body>

<!-- ************PROGRESSBAR LECTURE************************* -->
    
<div class="progressBarLecture"></div>

<!-- *************************************TEXT*************************************** -->
 <div class="card-img-overlay">
    <h5 class="card-title">Jon Doe</h5>
    <p class="card-text">Architecte DE HMONP</p>
 </div> 

 <!-- *********************************NAVBAR*************************************** -->
<nav>
  <ul>
    <li><a href="index.php">Acceuil</a></li>
    <li><a href="index.php?page=projectsPage">Projets</a></li>
    <li><a href="index.php?page=about">A propos</a></li>
    <li><a href="index.php?page=contact">Contact</a></li>
  </ul>
</nav>
<div class="btn_menu">
  <span class='toggle'></span>
</div>



  <main>
        <?php require $page ?>
        
  </main>

<!-- ************************************ARROW UP SECTION********************************** -->

<div class="arrowUp">
  <i id="arrowIcon"class="fas fa-angle-up"></i>
</div>




  <script type="text/javascript" src="js/layout.js"></script>
  <script type="text/javascript" src="js/app.js"></script>
  
</body>
</html>
