
 <!-- ********************TEXT****************************** -->
<div class="projectsBody">

    <div class="projectsText">
        <h3>Projets</h3>
        <p>Texte qui parle des projets   amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae.</p>
    </div>

 <!-- ********************IMG****************************** -->

    <div class="projectsImg">
        <img src="img\projet1.jpg" class="card-img-top" alt="maison verte">
        <h3>Suspendisse eget</h3>
        <img src="img\about.jpg" class="card-img-top" alt="batiment bleu">
        <h3>Nullam ac imperdiet</h3>
        <img src="img\projets1.jpg" class="card-img-top" alt="batiment historique">
        <h3>Mauris luctus</h3>
        <img src="img\projets.jpg" class="card-img-top" alt="maisons a la montagne">
        <h3>Ut tempor sapien</h3>
        <img src="img\projet1.jpg" class="card-img-top" alt="maison verte">
        <h3>Curabitur tincidunt</h3>
    </div>
    
</div>