 <!-- ********************BODY****************************** -->

<div class="projectsBody">
    <div class="projectsText">
        <h3>Projets</h3>
        <p>Texte qui parle des projets   amet, consectetur adipiscing elit. Cras rutrum, est maximus maximus bibendum, nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae nisl nibh aliquet ipsum, et accumsan ante nisl mollis turpis. Nullam ultrices rhoncus leo eget dapibus. Aliquam posuere justo ut condimentum fermentum. Aliquam magna nibh, mollis eget cursus non, rhoncus in massa. Donec imperdiet enim vel mauris euismod, sed porta magna pharetra. Aliquam ac i luctus et ultrices posuere cubilia curae.</p>
    </div>

    <div class="projectsImg">
        <img src="img\projet1.jpg" class="card-img-top" alt="maison verte">
        <h3>Projet1</h3>
        <img src="img\about.jpg" class="card-img-top" alt="batiment bleu">
        <h3>Projet2</h3>
        <img src="img\projets1.jpg" class="card-img-top" alt="batiment historique">
        <h3>Projet3</h3>
        <img src="img\projets.jpg" class="card-img-top" alt="maisons a la montagne">
        <h3>Projet4</h3>
        <img src="img\projet1.jpg" class="card-img-top" alt="maison verte">
        <h3>Projet5</h3>
    </div>
    
</div>